#!/bin/zsh

autoload -U colors
autoload -U compinit
fpath=(~/.zsh.d/functions $fpath)
autoload -U ~/.zsh.d/functions/*(:t)

colors
compinit

# for version control status :
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions
preexec_functions+='preexec_update_vc_vars'
precmd_functions+='precmd_update_vc_vars'
chpwd_functions+='update_current_vc_vars'

update_current_vc_vars
