#!/bin/zsh

#############
# 2 Aliases #
#############

alias ls='ls --classify --tabsize=0 --literal --color=auto --show-control-chars --human-readable'

alias grep='grep --color=auto'
alias svn='colorsvn'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'

alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'

alias c='clear'
alias less='less --quiet'
alias s='cd ..'

alias pk='packer --noedit'
alias py='python2.7'
alias pym='python2.7 -m'

alias df='df --human-readable'
alias du='du --human-readable'
alias duh="du -h | sort -h"
alias md='mkdir'
alias rd='rmdir'

alias ga='git add'
alias gt='git status'
alias gc='git commit'
alias gp='git pull'
alias gh='git push'

alias resource='source ~/.zshrc'

alias §='sudo'
alias §§='sudo -s'


alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -g .......='../../../../../..'
alias -g ........='../../../../../../..'
alias -g .........='../../../../../../../..'

alias x='emacsclient -c -n'
alias xx='sudo emacs'
