#!/bin/zsh

################
# 7 Completion #
################
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zshcache
zstyle ':completion:*::::' completer _expand _complete _ignored _approximate
zstyle -e ':completion:*:approximate:*' max-errors 'reply=( $(( ($#PREFIX + $#SUFFIX) / 3 )) )'
zstyle ':completion:*:functions' ignored-patterns '_*'

zstyle ':completion:*:*:*:default' menu yes select

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:*:kill:*:processes' command 'ps --forest -A -o pid,user,cmd'

zstyle ':completion:*:expand:*' tag-order all-expansions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters
zstyle ':completion:*' use-compctl false


zstyle ':completion:*:descriptions' format "${__green}└> %B%d%b ${_green}"
zstyle ':completion:*:messages' format "${__blue}└> %d ${_blue}"
zstyle ':completion:*:warnings' format "${__yellow}└> No matches for: %d ${_yellow}"
zstyle ':completion:*:corrections' format "${__red}└> %B%d (errors: %e)%b ${_red}"
zstyle ':completion:*:default' list-prompt "${__cyan}└> %S%M matches%s ${_cyan}"

zstyle ':completion:*:processes-names' command 'ps axho command' 

zstyle ':completion:*' hosts $(awk '/^[^#]/ {print $2 $3" "$4" "$5}' /etc/hosts | grep -v ip6- && grep "^#%" /etc/hosts | awk -F% '{print $2}')

zstyle ':completion:*:*:*:users' ignored-patterns \
         adm apache bin daemon games gdm halt ident junkbust lp mail mailnull \
         named news nfsnobody nobody nscd ntp operator pcap postgres radvd \
         rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs avahi-autoipd\
         avahi backup messagebus beagleindex debian-tor dhcp dnsmasq fetchmail\
         firebird gnats haldaemon hplip irc klog list man cupsys postfix\
         proxy syslog www-data mldonkey sys snort

zstyle ':completion:*:scp:*' tag-order files users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'
zstyle ':completion:*:scp:*' group-order files all-files users hosts-domain hosts-host hosts-ipaddr
zstyle ':completion:*:ssh:*' tag-order users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'

zstyle ':completion:*:ssh:*' group-order hosts-domain hosts-host users hosts-ipaddr
zstyle '*' single-ignored show
zstyle ':completion:*:rm:*' ignore-line yes
zstyle ':completion:*:mv:*' ignore-line yes
zstyle ':completion:*:cp:*' ignore-line yes

