#!/bin/zsh

#############
# 2 Aliases #
#############

alias ls='ls --classify --tabsize=0 --literal --color=auto --show-control-chars --human-readable'

alias grep='grep --color=auto'
alias svn='colorsvn'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'

alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'

alias c='clear'
alias s='cd ..'

alias pk='packer --noedit'
alias py='python2.7'
alias pym='python2.7 -m'
alias i='ipython'

alias df='df --human-readable'
alias du='du --human-readable'
alias duh="du -h | sort -h"
alias md='mkdir'
alias rd='rmdir'

alias ga='git add'
alias gt='git status -sb'
alias gc='git commit'
alias gp='git pull'
alias gh='git push'
alias gd='git diff --word-diff'
alias gk='git checkout'
alias gm='git merge'
alias gb='git branch'
alias gl='git log'
alias gcp='git cherry-pick'
alias gsf='git submodule foreach --recursive'
alias gsu='git submodule foreach --recursive git submodule update'

alias resource='source ~/.zshrc'

alias §='sudo'
alias §§='sudo -s'
alias ç='sudo'
alias Ç='sudo -s'
alias çu='sudo -u'
alias Çu='sudo -su'


alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -g .......='../../../../../..'
alias -g ........='../../../../../../..'
alias -g .........='../../../../../../../..'

alias x='emacsclient -c -n'
alias y='emacsclient -n'
alias xx='sudo emacs'
alias _='workon'
alias d='cdproject'
