#!/bin/zsh

#################
# 4 keybindings #
#################

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "\e[3~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey '^[[1;3D' emacs-backward-word
bindkey '^[[1;3C' emacs-forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey " " magic-space

case "$TERM" in
    *rxvt*)
	bindkey "\e[8~" end-of-line
	bindkey "\e[7~" beginning-of-line
	;;
    *freebsd*)
	bindkey "\e[H" beginning-of-line
	bindkey "\e[F" end-of-line
	;;
esac
