#!/bin/zsh

################
# 7 Completion #
################

expand-or-complete-with-dots() {
  echo -n "\e[31m......\e[0m"
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path .zshcache
zstyle ':completion:*' remove-all-dups yes
zstyle ':completion:*' verbose yes
zstyle ':completion:*::::' completer _expand _complete _ignored _approximate
zstyle -e ':completion:*:approximate:*' max-errors 'reply=( $(( ($#PREFIX + $#SUFFIX) / 3 )) )'
zstyle ':completion:*:functions' ignored-patterns '_*'


zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors 'reply=( "=(#b)(*$VAR)(?)*=00=36=31" )'
zstyle ':completion:*:*:*:*:commands' list-colors '=*=32=38'
zstyle ':completion:*:*:*:*:builtins' list-colors '=*=34=38'
zstyle ':completion:*:*:*:*:aliases' list-colors '=*=35=38'
zstyle ':completion:*:*:*:*:functions' list-colors '=*=36=38'
zstyle ':completion:*:*:*:*:directories' list-colors '=*=36=38'
zstyle ':completion:*:*:*:*:files' list-colors '=*=93=38'

zstyle ':completion:*:*:*:*:users' list-colors '=*=93=38'
zstyle ':completion:*:*:*:*:groups' list-colors '=*=94=38'

zstyle ':completion:*:*:*:*:corrections' list-colors '=*=31=38'
zstyle ':completion:*:*:*:*:processes' list-colors '=*=31=38'

zstyle ':completion:*:*:*:*:options' list-colors "=(#b) #(-#)*=36=31" #"=(#b) #([a-z]#)*=35=32"

# zstyle ':completion:*:*:task:*:default' list-colors "=(#b) #([^-]#)*=${__blue}=${__yellow}"
# zstyle ':completion:*:*:task:*:values' list-colors "=(#b) #([^-]#)*=${__blue}=${__yellow};${__red}"
# zstyle ':completion:*:*:task:*:commands' list-colors "=(#b) #([^-]#)*=${__blue}=${__yellow}"

zstyle ':completion:*' group-name ''

zstyle ':completion:*:*:*:default' menu auto select

zstyle ':completion:*:*:kill:*:processes' command 'ps --forest -A -o pid,user,cmd'

zstyle ':completion:*:expand:*' tag-order all-expansions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters


zstyle ':completion:*:descriptions' format "${bar}──≻${__green} %B%d%b ${_green}"
zstyle ':completion:*:messages' format "${bar}──≻${__blue} %d ${_blue}"
zstyle ':completion:*:warnings' format "${bar}──≻${__yellow} No matches for: %d ${_yellow}"
zstyle ':completion:*:corrections' format "${bar}──≻${__red} %B%d (errors: %e)%b ${_red}"
zstyle ':completion:*:default' list-prompt "${bar}──≻${__cyan} %S%M matches%s ${_cyan}"

zstyle ':completion:*:processes-names' command 'ps axho command' 

zstyle ':completion:*' hosts $(awk '/^[^#]/ {print $2 $3" "$4" "$5}' /etc/hosts | grep -v ip6- && grep "^#%" /etc/hosts | awk -F% '{print $2}')

zstyle ':completion:*:*:*:users' ignored-patterns \
         adm apache bin daemon games gdm halt ident junkbust lp mail mailnull \
         named news nfsnobody nobody nscd ntp operator pcap postgres radvd \
         rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs avahi-autoipd\
         avahi backup messagebus beagleindex debian-tor dhcp dnsmasq fetchmail\
         firebird gnats haldaemon hplip irc klog list man cupsys postfix\
         proxy syslog www-data mldonkey sys snort

zstyle ':completion:*:scp:*' tag-order files users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'
zstyle ':completion:*:scp:*' group-order files all-files users hosts-domain hosts-host hosts-ipaddr
zstyle ':completion:*:ssh:*' tag-order users 'hosts:-host hosts:-domain:domain hosts:-ipaddr"IP\ Address *'

zstyle ':completion:*:ssh:*' group-order hosts-domain hosts-host users hosts-ipaddr
zstyle '*' single-ignored show
zstyle ':completion:*:rm:*' ignore-line yes
zstyle ':completion:*:mv:*' ignore-line yes
zstyle ':completion:*:cp:*' ignore-line yes
